apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: post-api
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: "post-test-api/overlays"
    repoURL: https://github.com/esgungor/argo-cd-learning-session
    targetRevision: HEAD