apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-test-deployment
  labels:
    app: post-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: post-test
  template:
    metadata:
      labels:
        app: post-test
    spec:
      containers:
        - name: post-test
          image: enginsgungor/post-test:v2
          ports:
            - containerPort: 8080