apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: account-api
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: "account-test-api/overlays"
    repoURL: https://github.com/esgungor/argo-cd-learning-session
    targetRevision: HEAD